/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <string.h>

/* Header for class com_aplex_serialselect_SerialMode */

#ifndef _Included_com_aplex_serialselect_SerialMode
#define _Included_com_aplex_serialselect_SerialMode
#ifdef __cplusplus
extern "C" {
#endif

#include "android/log.h"
static const char *TAG="GPIO_aplex";
#define LOGE(fmt, args...) __android_log_print(ANDROID_LOG_ERROR, TAG, fmt, ##args)
/*
 * Class:     com_aplex_serialselect_SerialMode
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_aplex_serialselect_SerialMode_open
  (JNIEnv *env, jobject obj, jstring path, jint flag){
    int fd = -1;
    {
        jboolean iscopy;
        /**
         * 将Java的字符串转换成C中的字符串
         */
        const char *path_utf = (*env)->GetStringUTFChars(env, path, &iscopy);
        LOGE("Opening serial port %s with flags 0x%x", path_utf, O_RDWR | flag);
        fd = open(path_utf, O_RDWR | flag);
        LOGE("open() fd = %d", fd);
        /**
         * 和前面的GetStringUTFChars一对用法，相当于malloc和free
         */
        (*env)->ReleaseStringUTFChars(env, path, path_utf);
        if (fd == -1)
        {
            // Throw an exception
            LOGE("Cannot open port");
            // TODO: throw an exception
            return -1;
        }
    }
  return (jint)fd;
}

/*
 * Class:     com_aplex_serialselect_SerialMode
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_aplex_serialselect_SerialMode_close
  (JNIEnv *env, jobject obj, jint fd){
    close( (int)fd );
    LOGE("close() fd = %d", fd);
}

/*
 * Class:     com_aplex_serialselect_SerialMode
 * Method:    ioctl
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_com_aplex_serialselect_SerialMode_ioctl
  (JNIEnv *env, jobject obj, jint fd, jint cmd, jint value){
  return ioctl(fd, cmd, value);
}

#ifdef __cplusplus
}
#endif
#endif
