/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aplex_serialselect_SerialMode */

#ifndef _Included_com_aplex_serialselect_SerialMode
#define _Included_com_aplex_serialselect_SerialMode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aplex_serialselect_SerialMode
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_aplex_serialselect_SerialMode_open
  (JNIEnv *env, jobject obj, jstring path, jint flag){
  int fd = -1;
  return (jint)fd;
}

/*
 * Class:     com_aplex_serialselect_SerialMode
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_aplex_serialselect_SerialMode_close
  (JNIEnv *env, jobject obj, jint fd){

}

/*
 * Class:     com_aplex_serialselect_SerialMode
 * Method:    ioctl
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_com_aplex_serialselect_SerialMode_ioctl
  (JNIEnv *env, jobject obj, jint fd, jint cmd, jint value){
  return ioctl(fd, cmd, value);
}

#ifdef __cplusplus
}
#endif
#endif
